version: 0.1

phases:
    install:
         commands:
            - apt-get -y update
            - apt-get -y install zip
            - apt-get install -y nodejs
            - npm i -g @angular/cli
            - npm install -g --unsafe-perm --verbose cordova
            - cd cordova-app && npm install
    build:
         commands:
          - cd cordova-app && cd src && ng build
          - cd cordova-app && cordova platform rm android && cordova platform add android
          - cd cordova-app && cordova build
    # post_build:
    #      commands:
            # - serverless deploy --stage dev --region us-east-1 --verbose

# artifacts:
#     files:
#          - cordova-app/publish.apk
#     discard-paths: yes